import { test, expect } from '@playwright/test';

/**
 * Grid first-paint benchmark (plan §11.2: "Grid first-paint on a
 * 1000-column-wide table < 1s").
 *
 * Tagged @bench so it only runs under `make bench`, which parses the emitted
 * GRID_FIRST_PAINT_MS line and appends it to bench/trend.csv.
 *
 * Fixture: cassyx_demo.wide_grid, generated by scripts/seed.sh at
 * SEED_WIDE_COLUMNS (default 1000) columns.
 */
test('@bench grid first paint on the 1000-column wide table', async ({ page }) => {
  const started = Date.now();
  await page.goto('/browse/cassyx_demo/wide_grid', { waitUntil: 'commit' });

  // First paint = the first data cell being visible, not the route resolving.
  const firstCell = page.getByTestId('grid-cell').first();
  await expect(firstCell).toBeVisible({ timeout: 30_000 });
  const elapsed = Date.now() - started;

  // Machine-readable line consumed by scripts/bench.sh.
  console.log(`GRID_FIRST_PAINT_MS=${elapsed}`);

  // Recorded either way; the assertion is the §11.2 target.
  expect(elapsed, 'grid first paint must stay under 1s').toBeLessThan(1000);
});
