package io.cassyx.bulk.impl.dsbulk;

import static org.assertj.core.api.Assertions.assertThat;

import io.cassyx.bulk.api.dsbulk.DsbulkJobSpec;
import io.cassyx.bulk.api.dsbulk.DsbulkOperation;
import io.cassyx.bulk.api.dsbulk.DsbulkPlan;
import io.cassyx.bulk.api.dsbulk.DsbulkProbe;
import io.cassyx.bulk.api.dsbulk.DsbulkSetting;
import io.cassyx.bulk.api.dsbulk.DsbulkSettingGroup;
import io.cassyx.core.api.ClusterFlavor;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/** The generated command, the generated HOCON, and the promise that neither leaks a credential. */
class DsbulkPlanAndCommandTest {

  private static final Path JOB_DIR = Path.of("/var/lib/cassyx/jobs/6c8f2a10");

  private static DsbulkPlan unloadPlan(Map<String, String> overrides) {
    DsbulkJobSpec spec = new DsbulkJobSpec(DsbulkOperation.UNLOAD, "demo", "users", null, "csv",
        "/data/exports/users", null, false, null, 10, overrides);
    return DsbulkPlanner.plan(spec, DsbulkProbe.UNKNOWN, JOB_DIR, "UNLOAD_6c8f2a10");
  }

  @Test
  @DisplayName("argv is the workflow, the familiar shortcuts, and -f pointing at the generated conf")
  void argvShape() {
    DsbulkPlan plan = unloadPlan(Map.of());
    assertThat(plan.argv())
        .containsSequence("unload")
        .containsSequence("-k", "demo")
        .containsSequence("-t", "users")
        .containsSequence("-c", "csv")
        .containsSequence("-url", "/data/exports/users")
        .containsSequence("-f", "/var/lib/cassyx/jobs/6c8f2a10/dsbulk.conf");
    assertThat(plan.argv().get(0)).isEqualTo("unload");
  }

  @Test
  @DisplayName("the command line is copyable and shell-safe")
  void commandIsCopyable() {
    DsbulkJobSpec spec = new DsbulkJobSpec(DsbulkOperation.UNLOAD, "demo", "users",
        null, "csv", "/data/my exports", null, false, null, 10, Map.of());
    DsbulkPlan plan = DsbulkPlanner.plan(spec, DsbulkProbe.UNKNOWN, JOB_DIR, "id");
    assertThat(plan.command()).startsWith("dsbulk unload ").contains("'/data/my exports'");
    assertThat(DsbulkCommandBuilder.shellQuote("it's")).isEqualTo("'it'\\''s'");
    assertThat(DsbulkCommandBuilder.shellQuote("")).isEqualTo("''");
    assertThat(DsbulkCommandBuilder.shellQuote("plain/path-1.csv")).isEqualTo("plain/path-1.csv");
  }

  @Test
  @DisplayName("a query-driven unload uses -query, not -k/-t")
  void queryShortcut() {
    DsbulkJobSpec spec = new DsbulkJobSpec(DsbulkOperation.UNLOAD, null, null,
        "SELECT id FROM demo.users", "json", "/out", null, false, null, 10, Map.of());
    DsbulkPlan plan = DsbulkPlanner.plan(spec, DsbulkProbe.UNKNOWN, JOB_DIR, "id");
    assertThat(plan.argv()).containsSequence("-query", "SELECT id FROM demo.users");
    assertThat(plan.argv()).doesNotContain("-k");
    assertThat(DsbulkCommandBuilder.urlSetting(plan.settings())).isEqualTo("/out");
  }

  @Test
  @DisplayName("the HOCON uses fully-qualified paths - an unwrapped one is silently ignored by DSBulk")
  void hoconUsesFullyQualifiedPaths() {
    String hocon = unloadPlan(Map.of()).hocon();
    assertThat(hocon).contains("dsbulk.schema.keyspace = \"demo\"");
    assertThat(hocon).contains("dsbulk.connector.name = \"csv\"");
    // Driver settings live in the DRIVER's namespace, not under dsbulk.
    assertThat(hocon).contains("datastax-java-driver.basic.request.consistency = \"LOCAL_ONE\"");
    assertThat(hocon).contains("datastax-java-driver.advanced.protocol.compression = \"lz4\"");
    assertThat(hocon).doesNotContain("\ndriver.");
  }

  @Test
  @DisplayName("the HOCON explains itself: every derived value carries its rationale as a comment")
  void hoconIsSelfDocumenting() {
    String hocon = unloadPlan(Map.of()).hocon();
    assertThat(hocon).contains("# Generated by cassyx");
    assertThat(hocon).contains("# ");
    assertThat(hocon.lines().filter(l -> l.startsWith("# ")).count()).isGreaterThan(5);
  }

  @Test
  @DisplayName("literals are typed: numbers and booleans bare, everything else quoted")
  void hoconLiterals() {
    assertThat(DsbulkHocon.literal("32")).isEqualTo("32");
    assertThat(DsbulkHocon.literal("-1")).isEqualTo("-1");
    assertThat(DsbulkHocon.literal("1.5")).isEqualTo("1.5");
    assertThat(DsbulkHocon.literal("true")).isEqualTo("true");
    assertThat(DsbulkHocon.literal("[global,ranges]")).isEqualTo("[global,ranges]");
    assertThat(DsbulkHocon.literal("LOCAL_ONE")).isEqualTo("\"LOCAL_ONE\"");
    assertThat(DsbulkHocon.literal("5 minutes")).isEqualTo("\"5 minutes\"");
    assertThat(DsbulkHocon.literal("")).isEqualTo("\"\"");
    assertThat(DsbulkHocon.literal(null)).isEqualTo("null");
    assertThat(DsbulkHocon.literal("a\"b\\c")).isEqualTo("\"a\\\"b\\\\c\"");
    assertThat(DsbulkHocon.quote("a\nb\tc\rd")).isEqualTo("\"a\\nb\\tc\\rd\"");
  }

  @Test
  @DisplayName("comments wrap rather than running off into a 400-column line")
  void commentsWrap() {
    String wrapped = DsbulkHocon.wrap("word ".repeat(60));
    assertThat(wrapped).contains("\n# ");
    assertThat(wrapped.lines()).allSatisfy(line -> assertThat(line.length()).isLessThanOrEqualTo(100));
  }

  @Test
  @DisplayName("secrets are masked in the plan, and restored only in the file on disk")
  void secretsAreMaskedInThePlanAndRestoredOnDisk() {
    DsbulkPlan plan = s3Plan(Map.of("s3.secretAccessKey", "REAL-SECRET", "s3.region", "eu-west-1"));

    assertThat(plan.maskedFields()).contains("s3.secretAccessKey").doesNotContain("s3.region");
    assertThat(plan.value("s3.secretAccessKey")).isEqualTo("***");
    assertThat(plan.hocon()).doesNotContain("REAL-SECRET").contains("***");
    assertThat(plan.command()).doesNotContain("REAL-SECRET");

    String real = DsbulkPlanner.realHocon(plan, Map.of("s3.secretAccessKey", "REAL-SECRET"));
    assertThat(real).contains("REAL-SECRET").doesNotContain("***");
    // The prefixed spelling must resolve to the same setting.
    assertThat(DsbulkPlanner.realHocon(plan, Map.of("dsbulk.s3.secretAccessKey", "REAL-SECRET")))
        .contains("REAL-SECRET");
  }

  /* ------------------------------------------------------------------------------------ s3 */

  private static DsbulkPlan s3Plan(Map<String, String> overrides) {
    DsbulkJobSpec spec = new DsbulkJobSpec(DsbulkOperation.UNLOAD, "demo", "users", null, "csv",
        "s3://exports/users", null, false, null, 10, overrides);
    return DsbulkPlanner.plan(spec, DsbulkProbe.UNKNOWN, JOB_DIR, "UNLOAD_6c8f2a10");
  }

  @Test
  @DisplayName("s3 region/profile/credentials become s3:// URL query parameters, not settings")
  void s3SettingsBecomeUrlParameters() {
    DsbulkPlan plan = s3Plan(Map.of(
        "s3.region", "eu-west-1",
        "s3.profile", "exports",
        "s3.accessKeyId", "AKIAEXAMPLE",
        "s3.clientCacheSize", "40"));

    // Only clientCacheSize is a real DSBulk 1.11 setting; the rest would be silently accepted and
    // ignored by Typesafe Config, which is exactly what makes writing them out dangerous.
    assertThat(plan.hocon()).contains("dsbulk.s3.clientCacheSize = 40");
    assertThat(plan.hocon()).doesNotContain("dsbulk.s3.region").doesNotContain("dsbulk.s3.profile");
    assertThat(plan.hocon()).doesNotContain("dsbulk.s3.accessKeyId");

    // The preview carries the masked key - the URL is now a secret carrier, so it must be masked
    // like one; the real credential only ever reaches the file the runner writes.
    assertThat(plan.hocon())
        .contains("s3://exports/users?region=eu-west-1&profile=exports&accessKeyId=***");
    assertThat(DsbulkPlanner.realHocon(plan, Map.of("s3.accessKeyId", "AKIAEXAMPLE")))
        .contains("s3://exports/users?region=eu-west-1&profile=exports&accessKeyId=AKIAEXAMPLE");

    // The fields survive in the settings list so the UI can still render and edit them.
    assertThat(plan.value("s3.region")).isEqualTo("eu-west-1");
  }

  @Test
  @DisplayName("a URL carrying credentials stays OFF the command line, where `ps` would expose it")
  void credentialledUrlsAreNotPutOnTheCommandLine() {
    DsbulkPlan withKey = s3Plan(Map.of("s3.region", "eu-west-1", "s3.accessKeyId", "AKIAEXAMPLE"));
    // DSBulk resolves -url ABOVE the -f file, so a masked URL here would override the real one.
    assertThat(withKey.argv()).doesNotContain("-url");
    assertThat(withKey.command()).doesNotContain("accessKeyId");

    DsbulkPlan regionOnly = s3Plan(Map.of("s3.region", "eu-west-1"));
    assertThat(regionOnly.argv()).containsSequence("-url", "s3://exports/users?region=eu-west-1");
  }

  @Test
  @DisplayName("an s3:// URL with no region warns, and settings DSBulk 1.11 lacks are dropped loudly")
  void s3WarningsAreExplicit() {
    assertThat(s3Plan(Map.of()).warnings())
        .anySatisfy(warning -> assertThat(warning).contains("s3:// URL needs a region"));
    assertThat(s3Plan(Map.of("s3.region", "eu-west-1")).warnings())
        .noneSatisfy(warning -> assertThat(warning).contains("needs a region"));

    DsbulkPlan withGhosts = s3Plan(Map.of(
        "s3.region", "eu-west-1", "s3.sessionToken", "tok", "s3.endpoint", "https://minio.local"));
    assertThat(withGhosts.warnings())
        .anySatisfy(warning -> assertThat(warning).contains("s3.sessionToken does not exist"))
        .anySatisfy(warning -> assertThat(warning).contains("s3.endpoint does not exist"));
    assertThat(withGhosts.hocon()).doesNotContain("sessionToken").doesNotContain("minio.local");
  }

  @Test
  @DisplayName("a URL the user parameterised themselves wins over the form fields")
  void explicitUrlParametersWin() {
    DsbulkJobSpec spec = new DsbulkJobSpec(DsbulkOperation.UNLOAD, "demo", "users", null, "csv",
        "s3://exports/users?region=us-east-2", null, false, null, 10, Map.of("s3.region", "eu-west-1"));
    DsbulkPlan plan = DsbulkPlanner.plan(spec, DsbulkProbe.UNKNOWN, JOB_DIR, "UNLOAD_x");
    assertThat(plan.hocon()).contains("s3://exports/users?region=us-east-2");
    assertThat(plan.hocon()).doesNotContain("eu-west-1");
    assertThat(plan.warnings()).noneSatisfy(w -> assertThat(w).contains("needs a region"));
  }

  @Test
  @DisplayName("non-s3 URLs and empty inputs pass through the translation untouched")
  void foldIsANoOpWhereItShouldBe() {
    assertThat(DsbulkS3Url.fold(java.util.List.of())).isEmpty();
    assertThat(DsbulkS3Url.fold(null)).isEmpty();
    // A file:// or plain path sink keeps its URL, and the s3 fields are still dropped: they are not
    // settings in ANY configuration, so writing them would be misleading wherever the sink points.
    DsbulkPlan local = unloadPlan(Map.of("s3.region", "eu-west-1"));
    assertThat(local.hocon()).contains("/data/exports/users").doesNotContain("dsbulk.s3.region");
    assertThat(local.warnings()).noneSatisfy(w -> assertThat(w).contains("s3://"));

    assertThat(DsbulkS3Url.withParameters("s3://b/o", Map.of())).isEqualTo("s3://b/o");
    // A value with URL metacharacters must not silently break the query string.
    assertThat(DsbulkS3Url.withParameters("s3://b/o", Map.of("secretAccessKey", "a/b+c=")))
        .isEqualTo("s3://b/o?secretAccessKey=a%2Fb%2Bc%3D");
    assertThat(DsbulkS3Url.withParameters("s3://b/o?", Map.of("region", "eu-west-1")))
        .isEqualTo("s3://b/o?region=eu-west-1");
    assertThat(DsbulkCommandBuilder.carriesCredentials(null)).isFalse();
  }

  @Test
  @DisplayName("anything that looks like a credential is treated as one")
  void secretDetection() {
    assertThat(DsbulkReference.isSecret("s3.accessKeyId")).isTrue();
    assertThat(DsbulkReference.isSecret("s3.secretAccessKey")).isTrue();
    assertThat(DsbulkReference.isSecret("driver.advanced.authProvider.password")).isTrue();
    assertThat(DsbulkReference.isSecret("dsbulk.monitoring.prometheus.push.password")).isTrue();
    assertThat(DsbulkReference.isSecret("batch.mode")).isFalse();
  }

  @Test
  @DisplayName("log.directory and engine.executionId are pinned to the job")
  void jobScopedSettings() {
    DsbulkPlan plan = unloadPlan(Map.of());
    assertThat(plan.value("log.directory")).isEqualTo("/var/lib/cassyx/jobs/6c8f2a10/logs");
    assertThat(plan.value("engine.executionId")).isEqualTo("UNLOAD_6c8f2a10");
  }

  @Test
  @DisplayName("a plan can be built with no job directory, for a pure preview")
  void previewWithoutAJobDirectory() {
    DsbulkJobSpec spec = DsbulkJobSpec.table(DsbulkOperation.UNLOAD, "demo", "users", "csv", "/out");
    DsbulkPlan plan = DsbulkPlanner.plan(spec, DsbulkProbe.UNKNOWN, null, null);
    assertThat(plan.argv()).containsSequence("-f", "dsbulk.conf");
    assertThat(plan.value("log.directory")).isNull();
  }

  @Test
  @DisplayName("settings can be read back by group, for the Advanced accordion")
  void groupingForTheUi() {
    DsbulkPlan plan = unloadPlan(Map.of());
    assertThat(plan.group(DsbulkSettingGroup.DRIVER)).isNotEmpty()
        .allSatisfy(s -> assertThat(s.path()).startsWith("driver."));
    assertThat(plan.group(DsbulkSettingGroup.SCHEMA)).extracting(DsbulkSetting::path).contains("schema.keyspace");
    assertThat(plan.value("nope.not.a.setting")).isNull();
  }

  @Test
  @DisplayName("warnings are honest and actionable")
  void warnings() {
    DsbulkProbe keyspaces =
        new DsbulkProbe(1, 4, ClusterFlavor.AMAZON_KEYSPACES, true, false, false, null, Map.of());
    assertThat(DsbulkPlanner.warnings(
            DsbulkJobSpec.table(DsbulkOperation.UNLOAD, "demo", "users", "csv", "/o"), keyspaces))
        .anySatisfy(w -> assertThat(w).contains("token()"));

    DsbulkProbe astra = new DsbulkProbe(3, 4, ClusterFlavor.ASTRA, true, false, true, null, Map.of());
    assertThat(DsbulkPlanner.warnings(
            DsbulkJobSpec.table(DsbulkOperation.LOAD, "demo", "users", "csv", "/i"), astra))
        .anySatisfy(w -> assertThat(w).contains("rate limiting"))
        .anySatisfy(w -> assertThat(w).contains("No explicit mapping"));

    DsbulkProbe counters = new DsbulkProbe(1, 4, ClusterFlavor.CASSANDRA, true, true, false, null, Map.of());
    assertThat(DsbulkPlanner.warnings(
            DsbulkJobSpec.table(DsbulkOperation.LOAD, "demo", "hits", "csv", "/i"), counters))
        .anySatisfy(w -> assertThat(w).contains("double-count"));

    DsbulkJobSpec countNoPartitions = new DsbulkJobSpec(DsbulkOperation.COUNT, "demo", "users", null,
        "csv", null, null, false, List.of("global"), 10, Map.of());
    assertThat(DsbulkPlanner.warnings(countNoPartitions, DsbulkProbe.UNKNOWN))
        .anySatisfy(w -> assertThat(w).contains("largest-partitions"));
  }
}
