package io.cassyx.bulk.impl.dsbulk;

import io.cassyx.bulk.api.dsbulk.DsbulkSetting;
import java.util.List;
import java.util.Map;

/**
 * Renders the per-job HOCON file (plan section 5.3, gotcha 1).
 *
 * <p>There is <b>no {@code conf/} directory when DSBulk is embedded</b>, so either every setting
 * goes on the command line or we generate a configuration file and point {@code -f} at it. cassyx
 * generates the file: a 40-setting command line is unreadable, and the file doubles as a
 * downloadable, reproducible artifact - hand it to someone with a DSBulk install and they get the
 * same job.
 *
 * <p>Written by hand rather than with Typesafe Config's own renderer, on purpose: this module must
 * not put {@code com.typesafe.config} on the classpath at all, since colliding with Spring's copy
 * of it is the whole reason DSBulk runs out of process (plan section 5.3, gotcha 2).
 */
public final class DsbulkHocon {

  private DsbulkHocon() {}

  /**
   * Renders {@code settings} as a HOCON document.
   *
   * @param secrets real values for masked settings, keyed by setting path; empty for a preview
   */
  public static String render(List<DsbulkSetting> settings, Map<String, String> secrets) {
    Map<String, String> overrides = secrets == null ? Map.of() : secrets;
    StringBuilder out = new StringBuilder(2048);
    out.append("# Generated by cassyx. Reproducible: `dsbulk <workflow> -f <this file>`.\n")
        .append("# Every value here is either a cassyx-derived default (plan section 5.3) or your own\n")
        .append("# override. Nothing is implicit.\n\n");

    for (DsbulkSetting setting : settings) {
      String value = overrides.getOrDefault(DsbulkReference.normalise(setting.path()), setting.value());
      if (setting.auto() && !setting.rationale().isEmpty()) {
        out.append("# ").append(wrap(setting.rationale())).append('\n');
      }
      out.append(DsbulkReference.toDsbulkPath(setting.path()))
          .append(" = ")
          .append(literal(value))
          .append('\n');
    }
    return out.toString();
  }

  /**
   * HOCON literal for {@code value}.
   *
   * <p>Numbers, booleans and list/object literals are emitted bare so DSBulk parses them as the type
   * it expects; everything else is a quoted string. Quoting a number is not harmless here - a
   * setting typed as {@code int} in DSBulk's reference config rejects {@code "32"} outright.
   */
  static String literal(String value) {
    if (value == null) {
      return "null";
    }
    String trimmed = value.trim();
    if (trimmed.isEmpty()) {
      return "\"\"";
    }
    if ("true".equals(trimmed) || "false".equals(trimmed) || "null".equals(trimmed)) {
      return trimmed;
    }
    if (trimmed.matches("-?\\d+") || trimmed.matches("-?\\d*\\.\\d+")) {
      return trimmed;
    }
    if ((trimmed.startsWith("[") && trimmed.endsWith("]"))
        || (trimmed.startsWith("{") && trimmed.endsWith("}"))) {
      return trimmed;
    }
    return quote(trimmed);
  }

  /** HOCON/JSON string quoting. */
  static String quote(String value) {
    StringBuilder out = new StringBuilder(value.length() + 8).append('"');
    for (int i = 0; i < value.length(); i++) {
      char c = value.charAt(i);
      switch (c) {
        case '"' -> out.append("\\\"");
        case '\\' -> out.append("\\\\");
        case '\n' -> out.append("\\n");
        case '\r' -> out.append("\\r");
        case '\t' -> out.append("\\t");
        default -> out.append(c);
      }
    }
    return out.append('"').toString();
  }

  /** Keeps generated comments inside the 100-column band the rest of the file lives in. */
  static String wrap(String text) {
    String single = text.replace('\n', ' ').replaceAll("\\s+", " ").trim();
    StringBuilder out = new StringBuilder(single.length() + 16);
    int lineLength = 0;
    for (String word : single.split(" ")) {
      if (lineLength > 0 && lineLength + word.length() + 1 > 96) {
        out.append("\n# ");
        lineLength = 0;
      } else if (lineLength > 0) {
        out.append(' ');
        lineLength++;
      }
      out.append(word);
      lineLength += word.length();
    }
    return out.toString();
  }
}
