-- cassyx baseline schema (H2, file mode).
--
-- Design notes:
--  * Every credential column is CIPHERTEXT produced by AES-256-GCM with the key from
--    CASSYX_SECRET_KEY (plan section 3). The *_iv columns hold the per-value 96-bit nonce; GCM
--    nonces must never repeat under one key, so they are stored per value, never derived.
--  * Nothing here ever leaves the API as a value: responses expose has_* booleans (plan section 2.3).
--  * Identifiers are opaque strings (UUIDs) generated by the application, not IDENTITY columns, so
--    rows can be created client-side and remain stable across an export/import.

CREATE TABLE cassyx_connection (
  id                      VARCHAR(36)   NOT NULL PRIMARY KEY,
  name                    VARCHAR(200)  NOT NULL,
  mode                    VARCHAR(20)   NOT NULL,   -- CASSANDRA | ASTRA | ADVANCED
  contact_points          VARCHAR(2000),            -- comma separated host:port
  local_datacenter        VARCHAR(200),
  protocol_version        INT,
  username                VARCHAR(200),

  -- AES-256-GCM ciphertext + nonce. Never returned to the client.
  password_cipher         VARBINARY(4096),
  password_iv             VARBINARY(16),

  -- Astra (plan sections 3 / 3.1)
  astra_database_id       VARCHAR(64),
  astra_token_cipher      VARBINARY(4096),
  astra_token_iv          VARBINARY(16),
  scb_acquisition_mode    VARCHAR(20),              -- AUTO_DOWNLOAD | UPLOAD | PATH
  scb_region              VARCHAR(100),
  scb_type                VARCHAR(20),              -- DEFAULT | CUSTOM  (never 'region')
  scb_custom_domain       VARCHAR(255),
  scb_path                VARCHAR(1000),            -- server-side path, allow-list checked
  scb_bundle_cipher       BLOB,                     -- encrypted bundle zip, cached per section 3.1
  scb_bundle_iv           VARBINARY(16),
  scb_bundle_fetched_at   TIMESTAMP,

  -- SSL / mTLS and SSH tunnel (NoSQL Manager parity, plan section 3)
  ssl_enabled             BOOLEAN       DEFAULT FALSE NOT NULL,
  truststore_cipher       BLOB,
  truststore_iv           VARBINARY(16),
  truststore_password_cipher VARBINARY(4096),
  truststore_password_iv  VARBINARY(16),
  keystore_cipher         BLOB,
  keystore_iv             VARBINARY(16),
  keystore_password_cipher VARBINARY(4096),
  keystore_password_iv    VARBINARY(16),
  ssh_host                VARCHAR(255),
  ssh_port                INT,
  ssh_username            VARCHAR(200),
  ssh_private_key_cipher  BLOB,
  ssh_private_key_iv      VARBINARY(16),

  advanced_config         CLOB,                     -- raw application.conf (HOCON) passthrough
  created_at              TIMESTAMP     NOT NULL,
  updated_at              TIMESTAMP     NOT NULL,
  last_connected_at       TIMESTAMP
);
CREATE UNIQUE INDEX ux_cassyx_connection_name ON cassyx_connection (name);

-- Saved / favourite scripts, with folders (plan section 8).
CREATE TABLE cassyx_script_folder (
  id          VARCHAR(36)  NOT NULL PRIMARY KEY,
  name        VARCHAR(200) NOT NULL,
  parent_id   VARCHAR(36),
  created_at  TIMESTAMP    NOT NULL,
  CONSTRAINT fk_script_folder_parent FOREIGN KEY (parent_id) REFERENCES cassyx_script_folder (id)
);
CREATE INDEX ix_cassyx_script_folder_parent ON cassyx_script_folder (parent_id);

CREATE TABLE cassyx_saved_script (
  id            VARCHAR(36)  NOT NULL PRIMARY KEY,
  name          VARCHAR(200) NOT NULL,
  folder_id     VARCHAR(36),
  connection_id VARCHAR(36),
  keyspace_name VARCHAR(200),
  body          CLOB         NOT NULL,
  favorite      BOOLEAN      DEFAULT FALSE NOT NULL,
  created_at    TIMESTAMP    NOT NULL,
  updated_at    TIMESTAMP    NOT NULL,
  CONSTRAINT fk_saved_script_folder FOREIGN KEY (folder_id) REFERENCES cassyx_script_folder (id),
  CONSTRAINT fk_saved_script_connection FOREIGN KEY (connection_id) REFERENCES cassyx_connection (id)
);
CREATE INDEX ix_cassyx_saved_script_folder ON cassyx_saved_script (folder_id);

-- Query history with timing (plan section 8).
CREATE TABLE cassyx_query_history (
  id             VARCHAR(36)  NOT NULL PRIMARY KEY,
  connection_id  VARCHAR(36),
  keyspace_name  VARCHAR(200),
  statement      CLOB         NOT NULL,
  consistency    VARCHAR(30),
  executed_at    TIMESTAMP    NOT NULL,
  duration_ms    BIGINT,
  row_count      BIGINT,
  succeeded      BOOLEAN      NOT NULL,
  error_message  VARCHAR(2000),
  tracing_id     VARCHAR(64),
  CONSTRAINT fk_query_history_connection FOREIGN KEY (connection_id) REFERENCES cassyx_connection (id)
);
CREATE INDEX ix_cassyx_query_history_executed_at ON cassyx_query_history (executed_at DESC);
CREATE INDEX ix_cassyx_query_history_connection ON cassyx_query_history (connection_id);

-- Job substrate (plan section 5.5): QUEUED -> RUNNING -> SUCCEEDED | FAILED | CANCELLED.
CREATE TABLE cassyx_job (
  id                VARCHAR(36)  NOT NULL PRIMARY KEY,
  type              VARCHAR(30)  NOT NULL,  -- UNLOAD | LOAD | COUNT | DUMP | COPY | IMPORT
  status            VARCHAR(20)  NOT NULL,
  connection_id     VARCHAR(36),
  keyspace_name     VARCHAR(200),
  table_name        VARCHAR(200),
  engine            VARCHAR(20),            -- NATIVE | DSBULK  (plan sections 5.2 / 5.3)
  settings_json     CLOB,                   -- resolved settings incl. derived defaults
  progress_percent  INT          DEFAULT 0 NOT NULL,
  rows_processed    BIGINT       DEFAULT 0 NOT NULL,
  splits_total      INT          DEFAULT 0 NOT NULL,
  splits_completed  INT          DEFAULT 0 NOT NULL,
  artifact_path     VARCHAR(1000),
  log_path          VARCHAR(1000),
  error_message     VARCHAR(4000),
  created_at        TIMESTAMP    NOT NULL,
  started_at        TIMESTAMP,
  finished_at       TIMESTAMP,
  CONSTRAINT fk_job_connection FOREIGN KEY (connection_id) REFERENCES cassyx_connection (id)
);
CREATE INDEX ix_cassyx_job_status ON cassyx_job (status);
CREATE INDEX ix_cassyx_job_created_at ON cassyx_job (created_at DESC);

-- Reusable job templates: persisted overrides of the derived DSBulk defaults (plan section 5.3).
CREATE TABLE cassyx_job_template (
  id            VARCHAR(36)  NOT NULL PRIMARY KEY,
  name          VARCHAR(200) NOT NULL,
  type          VARCHAR(30)  NOT NULL,
  engine        VARCHAR(20),
  settings_json CLOB         NOT NULL,
  created_at    TIMESTAMP    NOT NULL,
  updated_at    TIMESTAMP    NOT NULL
);
CREATE UNIQUE INDEX ux_cassyx_job_template_name ON cassyx_job_template (name);

-- The activated license (plan section 9). Single logical row, but keyed so history is retainable.
CREATE TABLE cassyx_license (
  id            VARCHAR(36)  NOT NULL PRIMARY KEY,
  license_key   CLOB         NOT NULL,   -- signed payload.signature; verified offline, Ed25519
  lic_code      VARCHAR(64),
  email         VARCHAR(320),
  holder_name   VARCHAR(200),
  edition       VARCHAR(40),
  seats         INT,
  issued_on     DATE,
  activated_at  TIMESTAMP    NOT NULL,
  active        BOOLEAN      DEFAULT TRUE NOT NULL
);
CREATE INDEX ix_cassyx_license_active ON cassyx_license (active);

-- Webhook idempotency (plan section 9.3): fulfilment must be idempotent on event.id.
CREATE TABLE cassyx_billing_event (
  event_id     VARCHAR(120) NOT NULL PRIMARY KEY,
  event_type   VARCHAR(120) NOT NULL,
  received_at  TIMESTAMP    NOT NULL,
  processed_at TIMESTAMP,
  status       VARCHAR(30)  NOT NULL,
  detail       VARCHAR(2000)
);
